### ISSUE TITLE
MS Teams notification reports build Passed when it Failed.

### ISSUE THREAD

**Issue by steven-geo** [buildkite-plugins/teams-notification-buildkite-plugin#5]
When using this plugin in a pipeline.yml as the last step with the following configuration, it reports a successful pipeline run even though it failed. Is there a recommended pattern for using this plug to send pipeline completion notifications? Thanks

  - wait: ~
    continue_on_failure: true

  - label: "Send Pipeline completion notification"
    key: notification
    plugins:
      - teams-notification:
          webhook_url: "*****************"
          message: $BUILDKITE_MESSAGE
    command:
      - exit 0

**Comment by tomowatt** [comment]
Hey @steven-geo 

Thanks for raising this, as Plugins are defined at the Step level and executed as a part of the Jobs, they cannot be called once a Pipeline has finished. So it is not possible to use the Plugin to report the end status of a Build.

The Plugin uses the `BUILDKITE_COMMAND_EXIT_STATUS` environment variable, which indicates the Status of the particular Step the Plugin is defined on.
And from your example, we noticed that `command: exit 0` which would explain why a failed Build would be reported as "Passed" as that Step would run correctly and be "Passed"

The code that that logic is here:
https://github.com/buildkite-plugins/teams-notification-buildkite-plugin/blob/dcef53baa8e2bce747a7d36e9a61171cdebea639/hooks/pre-exit#L24-L27

We'll close this issue for now as we've reached out to yourself with alternative methods for getting Build Event notifications into Microsoft Teams.

But please reach out again with any more questions or issues, as we are always happy to help!
